# Site settings
title:          Roman Writes
description:    "Roman Writes (Also: An Amateur Observes)"
#baseurl:        "/tale"
url:            "https://romanwrites.com"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Roman Adeis
  url:          https://romanwrites.com
  email:        romanadeis@protonmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title:output_ext
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale